services:
  # Rust 构建服务器
  rust-builder-1.88:
    image: rust-builder-1.88:1.88-alpine
    container_name: rust-builder-1.88
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/rust-builder-1.88:/usr/local/cargo
    working_dir: /workspace
    command: tail -f /dev/null
    labels:
      - "builder.type=rust"
      - "builder.version=1.88"
      - "builder.status=ready"

  hello-builder-3.18:
    image: hello-builder:3.18
    container_name: hello-builder-3.18
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: sleep infinity
    labels:
      - "builder.type=hello"
      - "builder.version=linux"
      - "builder.status=ready"

  # # Golang 构建服务器
  # golang-builder-1.24:
  #   image: golang-builder:1.24
  #   container_name: golang-builder-1.24
  #   restart: unless-stopped
  #   volumes:
  #     - ./volumes/workspace:/workspace
  #     - ./volumes/cache/golang-1.24:/go/pkg
  #   working_dir: /workspace
  #   command: tail -f /dev/null
  #   labels:
  #     - "builder.type=golang"
  #     - "builder.version=1.24"
  #     - "builder.status=ready"

  # # Node 构建服务器
  # node-builder-22:
  #   image: node-builder:22
  #   container_name: node-builder-22
  #   restart: unless-stopped
  #   volumes:
  #     - ./volumes/workspace:/workspace
  #     - ./volumes/cache/node-22:/root/.npm
  #   working_dir: /workspace
  #   command: tail -f /dev/null
  #   labels:
  #     - "builder.type=node"
  #     - "builder.version=22"
  #     - "builder.status=ready"

  # # Tauri 构建服务器
  # tauri-builder-latest:
  #   image: tauri-builder:latest
  #   container_name: tauri-builder-latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./volumes/workspace:/workspace
  #     - ./volumes/cache/tauri-latest-cargo:/usr/local/cargo
  #     - ./volumes/cache/tauri-latest-npm:/root/.npm
  #   working_dir: /workspace
  #   command: tail -f /dev/null
  #   labels:
  #     - "builder.type=tauri"
  #     - "builder.version=latest"
  #     - "builder.status=ready"

volumes:
  rust-cache-1.88:
  hello-cache-3.18:
  # golang-cache-1.24:
  # node-cache-22:
  # tauri-cache-latest-cargo:
  # tauri-cache-latest-npm:
