services:
  # Golang 构建服务器
  golang-builder-1.24:
    build:
      context: ./builders/golang
      dockerfile: Dockerfile.1.24
    container_name: golang-builder-1.24
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/golang-1.24:/go/pkg
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: tail -f /dev/null
    labels:
      - "builder.type=golang"
      - "builder.version=1.24"
      - "builder.status=ready"

  # Node 构建服务器
  node-builder-22:
    build:
      context: ./builders/node
      dockerfile: Dockerfile.22
    container_name: node-builder-22
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/node-22:/root/.npm
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: tail -f /dev/null
    labels:
      - "builder.type=node"
      - "builder.version=22"
      - "builder.status=ready"

  # Rust 构建服务器
  rust-builder-latest:
    build:
      context: ./builders/rust
      dockerfile: Dockerfile.latest
    container_name: rust-builder-latest
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/rust-latest:/usr/local/cargo
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: tail -f /dev/null
    labels:
      - "builder.type=rust"
      - "builder.version=latest"
      - "builder.status=ready"

  # Tauri 构建服务器
  tauri-builder-latest:
    build:
      context: ./builders/tauri
      dockerfile: Dockerfile.latest
    container_name: tauri-builder-latest
    restart: unless-stopped
    volumes:
      - ./volumes/workspace:/workspace
      - ./volumes/cache/tauri-latest-cargo:/usr/local/cargo
      - ./volumes/cache/tauri-latest-npm:/root/.npm
      - ./volumes/artifacts:/artifacts
    working_dir: /workspace
    command: tail -f /dev/null
    labels:
      - "builder.type=tauri"
      - "builder.version=latest"
      - "builder.status=ready"

volumes:
  golang-cache-1.24:
  node-cache-22:
  rust-cache-latest:
  tauri-cache-latest-cargo:
  tauri-cache-latest-npm: 