[config]
default_to_workspace = false

[tasks.dev]
description = "Development workflow - clean, check, test, and build"
dependencies = [
    "clean",
    "check-format", 
    "clippy",
    "test",
    "build"
]

[tasks.clean]
description = "Clean build artifacts"
command = "cargo"
args = ["clean"]

[tasks.check-format]
description = "Check code formatting"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.format]
description = "Format code"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
description = "Run clippy lints"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-W", "clippy::complexity", "-W", "clippy::correctness", "-A", "dead_code", "-A", "unused_imports", "-A", "unused_variables"]

[tasks.test]
description = "Run tests"
command = "cargo"
args = ["test"]

[tasks.build]
description = "Build the project"
command = "cargo"
args = ["build"]

[tasks.run]
description = "Run the application with help"
command = "cargo"
args = ["run", "--", "--help"]

[tasks.release]
description = "Build release version"
command = "cargo"
args = ["build", "--release"]

[tasks.check]
description = "Check compilation without building"
command = "cargo"
args = ["check"]

[tasks.watch]
description = "Watch for changes and rebuild"
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "check", "-x", "test"]

[tasks.install-deps]
description = "Install development dependencies"
script = [
    "cargo install cargo-watch",
    "cargo install cargo-make"
] 