name: "space_01"
description: "space_01"

projects:
  - name: "project_01"
    description: "project_01"
    type: "golang"
    source:
      git_repo: "https://github.com/confkit/engine.git"
      git_branch: "main"
      clone_depth: 1