name: "hello"
description: "hello"

projects:
  - name: "hello"
    description: "hello demo"
    type: "hello"
    source:
      git_repo: "https://github.com/confkit/engine.git"
      git_branch: "main"
      clone_depth: 1