#!/bin/bash

echo "📚 CCDD Helper - Claude Code 深度开发工作流系统"
echo "================================================"
echo ""
echo "🤔 核心理念: 深度思考模式下的智能开发助手"
echo "🔐 安全优先: Git 安全边界 + 用户完全控制"  
echo "🎯 项目导向: 功能→议题的清晰开发路径"
echo ""
echo "💬 智能对话命令"
echo "  /dd:chat                    - 支持多行输入的深度对话系统"
echo "                              - 基于项目上下文的智能分析"
echo "                              - 技术咨询、方案设计、问题诊断"
echo ""
echo "🎯 核心开发工作流 (22 个智能命令)"
echo "  1. /dd:init                    - 初始化项目 (支持 --analyze 参数)"
echo "     /dd:init                    # 新项目初始化"
echo "     /dd:init --analyze          # 分析现有项目并初始化"
echo "  2. /dd:prd                     - 项目需求设计"
echo "  3. /dd:ui                      - UI 原型设计 (可选)"
echo "  4. /dd:framework-init          - 项目框架设计"
echo "  5. /dd:prd-decompose          - 需求拆解 (基于 PRD 拆解功能模块)"
echo "  6. /dd:feature-add <功能>       - 添加新功能"
echo "  7. /dd:feature-decompose <功能>  - 功能拆解多个议题"
echo "  8. /dd:issue-start <功能>:<议题> - 开始执行具体议题"
echo "  9. /dd:issue-update <功能>:<议题> - 更新议题进度"
echo " 10. /dd:feature-update <功能>    - 更新功能状态"
echo " 11. /dd:code-reflect            - 代码变更反思分析"
echo ""
echo "📄 功能管理命令"
echo "  /dd:feature-add <名称>      - 创建新功能, 深度分析需求"
echo "  /dd:feature-decompose <名称> - 功能议题分解"
echo "  /dd:feature-start <名称>    - 开始功能开发（需已完成议题拆解）"
echo "  /dd:feature-update <名称>   - 批量更新功能和子议题状态"
echo "  /dd:feature-status          - 查看所有功能状态和进度"
echo "  /dd:feature-refactory <名称> - 功能重构优化"
echo "  /dd:feature-remove <名称>   - 删除功能"
echo ""
echo "📝 议题管理命令"
echo "  /dd:issue-start <功能>:<议题>  - 开始执行议题, 深度思考实现"
echo "  /dd:issue-update <功能>:<议题> - 智能更新议题状态和进度"
echo ""
echo "🔍 代码质量命令"
echo "  /dd:code-reflect            - 基于Git变更进行代码反思分析"
echo ""
echo "🏗️ 架构管理命令"
echo "  /dd:framework-init          - 深度思考技术选型和架构"
echo "  /dd:framework-audit         - 深度分析架构合理性"
echo "  /dd:framework-adjust        - 基于审计调整架构"
echo "  /dd:prd-decompose          - 需求拆解（基于 PRD 拆解功能模块）"
echo ""
echo "🔄 状态和工具命令"
echo "  /dd:help                    - 显示此帮助信息"
echo "  /dd:version                 - 版本信息"
echo "  /dd:status                  - 项目整体状态概览"
echo ""
echo "💡 深度思考模式特性"
echo "  • 🧠 每个命令都基于深度思考智能体执行"
echo "  • 🤝 AI 主动提出质疑和改进建议"
echo "  • 💬 与开发者深度讨论确认方案"
echo "  • 🔍 考虑长远影响和技术债务"
echo "  • ⚖️ 多维度分析技术、业务、用户价值"
echo ""
echo "🛡️ 安全保障"
echo "  • ❌ AI 完全禁止 Git 写操作（add/commit/push/merge）"
echo "  • 🔒 只读 Git 检查, 发现问题提示用户手动处理"
echo "  • 👤 用户保持代码仓库完全控制权, AI 只提供分析和建议"
echo "  • ⚠️ 所有 Git 建议操作都需要用户明确手动执行"
echo "  • 🔐 敏感信息和凭证绝对安全保护"
echo ""
echo "📋 五大核心工作流程"
echo "  新项目完整流程: "
echo "    /dd:init → /dd:prd → (/dd:ui) → /dd:prd-decompose → /dd:framework-init → /dd:feature-start"
echo "  旧项目初始化: "  
echo "    /dd:init --analyze → /dd:framework-audit → /dd:framework-adjust → /dd:feature-add → /dd:feature-start"
echo "  功能开发迭代: "
echo "    /dd:feature-add → /dd:feature-decompose → /dd:issue-start → /dd:issue-update → /dd:feature-update → /dd:code-reflect"
echo "  架构管理流程: "
echo "    /dd:framework-init → /dd:framework-audit → /dd:framework-adjust → /dd:feature-start"
echo "  质量管理流程: "
echo "    /dd:code-reflect → /dd:feature-refactory → /dd:status → /dd:chat"
echo ""
echo "🎯 建议的下一步操作: "
echo "  • 新项目: /dd:init"
echo "  • 已有项目: /dd:init --analyze" 
echo "  • 智能对话: /dd:chat"
echo "  • 查看状态: /dd:status"
echo "  • 了解更多: 查看 CLAUDE.md 文档"
echo ""
echo "📖 可视化文档和帮助"
echo "  • 查看所有命令和工作流: 打开 .claude/ui/properties/index.html"
echo "  • 启动本地服务器: cd .claude/ui/properties && node server.js"
echo "  • 然后访问: http://localhost:3000"
echo ""
echo "🌟 CCDD Helper 的核心价值"
echo "  ✅ 深度思考驱动的智能决策"
echo "  ✅ 安全优先的开发环境"
echo "  ✅ 结构化的功能→议题开发路径"
echo "  ✅ AI 辅助的质量保证和代码审查"
echo "  ✅ 灵活的多行输入命令支持"

exit 0